config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: "home#index"

  get "/disclaimer", to: "disclaimer#index"

  resource :search, only: :show
  resources :book_ratings, only: :index
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  def show
    return unless ISBN.valid?(params[:isbn])

    @isbn = ISBN.thirteen(params[:isbn])
    @book = BookSearcher.search(@isbn)
  end
end

app/views/searches/_book_info.html.slim
ul.book-info
  li.book-info__image
    = image_tag @book.cover_image
  li.book-info__title
    span.book-info__title-label
      | タイトル:
    span.book-info__title-content
      = @book.title
  li.book-info__author
    span.book-info__author-label
      | 著者:
    span.book-info__author-content
      = @book.author
  li.book-info__publisher
    span.book-info__publisher-label
      | 出版社:
    span.book-info__publisher-content
      = @book.publisher
  li.book-info__release-date
    span.book-info__release-date-label
      | 出版年:
    span.book-info__release-date-content
      = @book.release_date

app/views/searches/_form.html.slim
= form_with url: search_path, method: :get, local: true do |f|
  .search.field.has-addons
    .control
      .search__input.input
        = f.text_field :isbn, placeholder: "ISBN(ハイフン無しでも可)", required: true
    .control
      .search__btn
        = button_tag type: 'submit', name: nil, class: 'button is-light' do
          i.fa.fa-search

app/views/searches/_navbar.html.slim
.navbar
  .navbar-brand
    .navbar-item
      = link_to image_tag("icon.png"), "/"
    = render "form"

app/views/searches/_search_result.html.slim
= content_for(:html_title) { "『#{@book.title}』の複数サービスでの評価一覧 | 本の星" }

.search-result
  = render "book_info"
  = render_async book_ratings_path(isbn13: @book.isbn13) do
    | <div class="loading"><i class="fa fa-spinner fa-spin fa-5x" aria-hidden="true"></i></div>

app/views/searches/show.html.slim
= render "navbar"

- if !ISBN.valid?(@isbn)
    p 有効なISBN-13または有効なISBN-10を入力してください
- elsif @book.nil?
    p 書籍が見つかりませんでした
- elsif !@book.nil?
  = render "search_result"

.foot
  .foot__disclaimer-link
    = link_to "免責事項", disclaimer_path
  .foot__copyright
    .foot__copyright-mark
      i.fa.fa-copyright
    .foot__name
      | kaitoyoshioka
    .foot__year
      = Date.today.year